🔀 :: 자습 신청 디테일
DSM-FLOW/DMS-iOS pull request #158
Opened 2022-12-28 10:58 UTC by baekteun

## 개요
<img src="https://user-images.githubusercontent.com/74440939/209801779-a82bf59e-de20-456a-b4fd-4be6034cd91b.png" width="150" />

이런 느낌

2022-12-28 11:17 UTC, kimdaehee0824 approved these changes

2022-12-28 12:21 UTC, sian7563 approved these changes

2022-12-29 13:16 UTC, kimdaehee0824 requested changes

2022-12-29 13:16 UTC, kimdaehee0824 commented on Projects/Features/ApplyFeature/Sources/StudyRoomDetail/StudyRoomDetailView.swift
> +                .edgesIgnoringSafeArea(.bottom)
이거랑 탭바 숨기는거랑 결합해서 엄청난 오류를 발생시킴, 텝이 지멋대로 가서 안된다던가 하는 그런 엄청난 오류가 생겨서 탭바 관련 로직 수정 요청함

2023-01-03 06:44 UTC, kimdaehee0824 approved these changes

2023-01-03 06:44 UTC, merged