merge :: (#278) 주말 외출 기능 개발
DSM-FLOW/DMS-iOS pull request #280
Opened 2024-04-25 08:29 UTC by ray3238

## 개요
- 주말 외출 기능을 개발합니다

## 작업사항
- 주말 외출 기능의 디자인 수정 및 API 연동

## UI

https://github.com/team-aliens/DMS-iOS/assets/127665596/e993ddb6-fe63-410e-865d-b35a9db8221c

2024-04-25 08:46 UTC, baekteun commented on Projects/Feature/OutingApplyFeature/Sources/Component/OutingApplicationView.swift
> +        _ status: Bool? = false
status라는 변수명으로는 bool값인지를 바로 알 수가 없는데 is나 should를 prefix로 붙여서 변수명 작명해주시는게 어떤가요

2024-04-25 08:47 UTC, baekteun commented on Projects/Feature/OutingApplyFeature/Sources/Component/OutingApplicationView.swift
>              DMSFormTextField(placeholder, text: $text)
```suggestion
                    .padding(.bottom, 8)

                if self.status ?? false {
                    Text("*")
                        .dmsFont(.body(.body3), color: .PrimaryVariant.primary)
                }
            }

            DMSFormTextField(placeholder, text: $text)
```
스타일 가이드 바뀐지는 잘 모르긴하지만 스유 스타일은 이런 스타일로 가던것으로 기억해요

2024-04-25 08:49 UTC, baekteun commented on Projects/Feature/OutingApplyFeature/Sources/OutingApplyComponent.swift
> +                outingApplicationUseCase: dependency.outingApplicationUseCase
어.. 새로운 스타일 가이드가 정립되었나요.?>?
https://github.com/team-aliens/DMS-iOS/wiki/Team-Aliens--SwiftStyleGuide

2024-04-25 08:51 UTC, baekteun commented on Projects/Feature/OutingApplyFeature/Sources/OutingApplyViewModel.swift
> +        }
이 친구 실행되나요? fetchAllStudent 하기 전에 실행돼서 동작하지 않을거같아서요

2024-04-25 08:53 UTC, baekteun commented on Projects/Feature/OutingApplyFeature/Sources/OutingApplyView.swift
> +                                )
```suggestion
                                Button(
                                    "확인",
                                    role: .destructive,
                                    action: {
                                        if viewModel.outingApplicationTimeStatus && viewModel.outingTypeTitleApplicationStatus {
                                            viewModel.confirmOutingApplicationItemButtonDidClicked()
                                        } else {
                                            viewModel.isErrorOcuured = true
                                            viewModel.errorMessage = "필수 입력 항목을 확인해주세요."
                                        }
                                    }
                                )
```
https://github.com/team-aliens/DMS-iOS/wiki/Team-Aliens--SwiftStyleGuide#%EC%A4%84%EB%B0%94%EA%BF%88
스타일 가이드상 이렇게 하는게 적절할거같아요

2024-04-25 08:53 UTC, baekteun commented on Projects/Feature/OutingApplyFeature/Sources/OutingApplyView.swift
> +                                )
```suggestion
                                Button("확인", role: .destructive) {
                                    if viewModel.outingApplicationTimeStatus && viewModel.outingTypeTitleApplicationStatus {
                                        viewModel.confirmOutingApplicationItemButtonDidClicked()
                                    } else {
                                        viewModel.isErrorOcuured = true
                                        viewModel.errorMessage = "필수 입력 항목을 확인해주세요."
                                    }
                                }
```
아니면 아예 이렇게 가도 괜찮을거같아요

2024-04-25 08:57 UTC, baekteun commented on Projects/Feature/OutingApplyFeature/Sources/Component/OutingTimePickerView.swift
> +                .padding(.horizontal, 24)
```suggestion
            DMSWideButton(text: "확인", color: .PrimaryVariant.primary) {
                viewModel.outingHourSelectTime = outingHourSelectTime + 1
                viewModel.outingMinuteSelectTime = outingMinuteSelectTime
                viewModel.arrivalHourSelectTime = arrivalHourSelectTime + 1
                viewModel.arrivalMinuteSelectTime = arrivalMinuteSelectTime
                timeText = viewModel.outingApplicationTime
                viewModel.outingApplicationTimeStatus = true
            }
            .padding(.top, 30)
            .padding(.horizontal, 24)
```
trailing closure 쓰시면 modifier더 깔끔하게 쓰실 수 있을거같아요

2024-04-25 10:22 UTC, ray3238 commented on Projects/Feature/OutingApplyFeature/Sources/OutingApplyViewModel.swift
> +        }
실행 안되고, 사용하지 않아도 되는 코드라서 삭제헀습니다!

2024-04-25 10:29 UTC, ray3238 commented on Projects/Feature/OutingApplyFeature/Sources/Component/OutingTimePickerView.swift
> +                .padding(.horizontal, 24)
아 그렇군요! 감사합니다

2024-04-25 10:30 UTC, ray3238 commented on Projects/Feature/OutingApplyFeature/Sources/OutingApplyView.swift
> +                                )
앞으로는 스타일 가이드 잘 보고 개발하겠습니다 ㅠㅠ

2024-04-26 03:14 UTC, DSMInhyeKang reviewed
@ray3238 
- 변수명 isStatus ➡️ isRequired, isNecessary 등 직관적인 이름으로 변경
- 외출/도착 시간 hour/time ➡️ Date 타입 + DateFormatter 활용 or struct 새로 파서 활용

2024-04-26 03:15 UTC, DSMInhyeKang requested changes

2024-04-26 03:15 UTC, DSMInhyeKang commented on Projects/App/Derived/InfoPlists/DMS-AliensTests-Info.plist
외출 기능까지 포함해서 배포한 다음에 CI/CD 다시 고쳐야 되니까 원상복구

2024-05-10 10:45 UTC, DSMInhyeKang commented on Projects/Domain/OutingDomain/Interface/Error/OutingDomainError.swift
> +            return "외출 신청이 없습니다."
신청한 외출 내역이 없습니다.

2024-05-10 10:56 UTC, DSMInhyeKang requested changes

2024-05-10 10:56 UTC, DSMInhyeKang commented on Projects/Feature/OutingApplyFeature/Sources/Component/OutingTextFieldView.swift
> +                if self.isRequired ?? false {
```suggestion
                if isRequired {
```

2024-05-10 10:56 UTC, DSMInhyeKang commented on Projects/Feature/OutingApplyFeature/Sources/Component/OutingApplyNoticeView.swift
> -        .padding(.bottom, 25)
디자인이랑 패딩이 안 맞아요.

2024-05-10 11:12 UTC, DSMInhyeKang approved these changes

2024-05-10 11:16 UTC, merged