merge :: (#282) fcm연동
DSM-FLOW/DMS-iOS pull request #285
Opened 2024-08-06 02:11 UTC by ray3238

## 개요
- fcm을 연동합니다.

## 작업사항
- fcm을 연동합니다.

## UI
![IMG_9379](https://github.com/user-attachments/assets/6ec701c7-f278-4d79-b645-a52e536fa2a2)

2024-08-06 02:13 UTC, baekteun submitted a review, later dismissed

2024-08-06 02:13 UTC, baekteun commented on Projects/App/Sources/Application/AppDelegate.swift
> +        print("Firebase registration token: \(token)")
print 지우는게 좋아보여요

2024-08-06 02:13 UTC, baekteun commented on Projects/App/Sources/Application/AppDelegate.swift
> +        print("APNS token: \(deviceToken)")
print 지우는게 좋아보여요

2024-08-06 02:15 UTC, baekteun commented on Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
> +    static let FirebaseMessaging = Package.remote(url: "https://github.com/firebase/firebase-ios-sdk", requirement: .upToNextMajor(from: "9.5.0"))
버전이 너무 낮은거같은데 9.5.0이 맞나요? 최근 10.x대 업데이트에 privacy manifest 추가하는 버전도 나왔어가지고 9.5.0으로 괜찮나요?

2024-08-06 09:51 UTC, ray3238 commented on Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
> +    static let FirebaseMessaging = Package.remote(url: "https://github.com/firebase/firebase-ios-sdk", requirement: .upToNextMajor(from: "9.5.0"))
다른 프로젝트에서 push 알림 기능만 사용하는데에는 9.5.0 버전으로도 괜찮았어서 사용했습니다.
버전 업그레이드가 되면서 privacy manifest라는 기능이 생겼는지는 몰랐네요. 조금 더 공부해보겠습니다.

2024-08-06 09:57 UTC, baekteun approved these changes
CI는 언제 고쳐지는지 눈물나네요

2024-08-08 23:47 UTC, DSMInhyeKang commented on Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
> +    static let FirebaseMessaging = Package.remote(url: "https://github.com/firebase/firebase-ios-sdk", requirement: .upToNextMajor(from: "9.5.0"))
@ray3238 심사 올리기 전에 한 번 확인하고 올리는 게 나을 것 같아요.
https://github.com/firebase/firebase-ios-sdk/issues/11490

2024-08-08 23:57 UTC, DSMInhyeKang requested changes
페메로 말한 거 확인되면 다시 알려주세요

2024-08-13 02:29 UTC, DSMInhyeKang approved these changes

2024-08-13 02:39 UTC, baekteun approved these changes

2024-08-22 12:56 UTC, merged