merge :: FIndID Feature
DSM-FLOW/DMS-iOS pull request #75
Opened 2022-10-21 06:33 UTC by kimdaehee0824

## 개요
FIndID Feature름 만들었습니다
스위프트UI를 해본지 오래되서 시간이 걸렸습니다

## 작업사항
- FIndID UI
- FIndID ViewModel 대충
- FindID Component

2022-10-21 06:44 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/FindIDView.swift
> +            .disabled(!viewModel.isNavigateSignup)
네..? isNavigateSignup을 Disabled 조건으로 준다고요..?

2022-10-21 06:44 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/FindIDViewModel.swift
> +        guard isNavigateSignup else { return }
어..? 이게 왜 조건..?

2022-10-21 06:44 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/FindIDViewModel.swift
> +    @Published var isNavigateSignup = false
isNavigateSignup은 Signup View로 NavigationLink을 통해 넘어갈때 쓰는 binding입니다

2022-10-21 06:44 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/SchoolSelectButtonView.swift
> +                Menu {
들겨쓰기 맞춰주세요!

2022-10-21 06:44 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/SchoolSelectButtonView.swift
> +                    .foregroundColor(.GrayScale.gray5 )
이러면 foregroundColor를 두 번 쓴건데요..?

2022-10-21 06:44 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/FindIDViewModel.swift
> +            number: Int(number)!))) { [weak self] _ in
force unwrapping은 좀 두려움의 여지가 있습니다. guard 로 걸러줍시다

2022-10-21 06:44 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/FindIDView.swift
> +struct FindIdView: View {
파일명이랑 맞춰주세요!

2022-10-21 06:44 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/FindIDView.swift
> +    }
nested..는 일단 가장 상위로 올리는거 어떄요?

2022-10-21 06:54 UTC, kimdaehee0824 commented on Projects/Features/FindIDFeature/Sources/FindIDViewModel.swift
> +        guard isNavigateSignup else { return }
엄......

2022-10-21 06:55 UTC, kimdaehee0824 commented on Projects/Features/FindIDFeature/Sources/FindIDView.swift
> +            .disabled(!viewModel.isNavigateSignup)
잠만잠만

2022-10-22 10:18 UTC, sian7563 approved these changes

2022-10-22 10:19 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/SchoolSelectButtonView.swift
> +    @State var selectedColor = "학교를 선택해 주세요"
selectedColor..? 네이밍 의도를 알 수 없어요

2022-10-22 10:19 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/SchoolSelectButtonView.swift
> +                        ForEach(schoolList, id: \.self) {
줄바꿈 해주세요!

2022-10-22 10:19 UTC, baekteun commented on Projects/Features/SigninFeature/Sources/SigninView.swift
>                      Text("자동로그인")
```suggestion
                    DMSCheckBox(isOn: $viewModel.isOnAutoSignin)

                    Text("자동로그인")
```
헣

2022-10-22 10:21 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/SchoolSelectButtonView.swift
> +                    .foregroundColor(.GrayScale.gray5 )
아래 .foreground 죽이죠

2022-10-22 10:24 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/SchoolSelectButtonView.swift
> +}
학교 선택한 후의... 뭐가.. 없어요....?

2022-10-22 12:40 UTC, baekteun requested changes

2022-10-22 12:40 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/FindIDComponent.swift
> +    var checkSchoolCodeUseCase: any CheckSchoolCodeUseCase { get }
이 친구 안쓰는데 왜 주입 받은건가요?

2022-10-23 03:31 UTC, kimdaehee0824 commented on Projects/Features/FindIDFeature/Sources/FindIDComponent.swift
> +    var checkSchoolCodeUseCase: any CheckSchoolCodeUseCase { get }
나중에 쓰려고 주입한거에여

2022-10-23 03:39 UTC, kimdaehee0824 commented on Projects/Features/FindIDFeature/Sources/FindIDComponent.swift
> +    var checkSchoolCodeUseCase: any CheckSchoolCodeUseCase { get }
아 잘못넣었네

2022-10-23 04:32 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/FindIDViewModel.swift
> +        }
순환 참조 조심!

2022-10-23 04:36 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/SchoolSelectButtonView.swift
> +            }
```suggestion
                            placeholderText = schoolList.name
                            onCommit(schoolList)
                        })
                    }
                    .labelsHidden()
                    .pickerStyle(InlinePickerStyle())
                } label: {
                    Image(systemName: "chevron.down")
                        .foregroundColor(.GrayScale.gray5)
                        .frame(width: 24, height: 24)
                }
            }
```
이거

2022-10-23 04:36 UTC, baekteun commented on Projects/Features/FindIDFeature/Sources/SchoolSelectButtonView.swift
> +
```suggestion
                    ForEach(schoolList) { school in
                        Button("\(school.name)", action: {
                            placeholderText = schoolList.name
                            onCommit(school)

```
혼동의 여지가 있어서 schoolList보다는 단일 단위로 school 어떠신지요?

2022-10-23 04:55 UTC, baekteun approved these changes

2022-10-23 05:00 UTC, closed without merging